server:
  port: 7070
spring:
  application:
    name: jmq-config-server
  cloud:
    config:
      server:
        git:
          uri:
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: root
      password: 123456